import re

path = 'AlbaManager_UserManual/AlbaPay_Calculations_Report_Full.md'
with open(path, 'r', encoding='utf-8') as f:
    text = f.read()

text = re.sub(r'1원 단위까지 깐깐하게 기본급을 산출합니다\.', '기본급을 산출합니다.', text)
text = re.sub(r'정확히 2,500,000원을 산출합니다\.', '2,500,000원으로 산출됩니다.', text)
text = re.sub(r'재직 비율\(`15/30 = 0\.5`\)을 정확히 산출하여', '재직 비율(`15/30 = 0.5`)을 산출하여', text)
text = re.sub(r'깎아내어 정확히 \*\*1,250,000원\*\*으로', '비례 산정하여 **1,250,000원**으로', text)
text = re.sub(r'비율\(`proRataRatio`\)을 소수점 아래까지 정확히 산출하여', '비율(`proRataRatio`)을 산출하여', text)
text = re.sub(r'기준으로 정확히 90% 감액된', '기준으로 90% 감액된', text)
text = re.sub(r'시급을 정확히 적용', '시급을 적용', text)
text = re.sub(r'과다/과소 지급 없이 1원 단위까지 정밀하게 정산됩니다\.', '과다/과소 지급 방지를 고려하여 정산됩니다.', text)
text = re.sub(r'무결성을 증명하기 위한 \*\*다양한 엣지 케이스 시나리오가 의도적으로 주입\*\*되어 있습니다\.', '다양한 상황 대응을 시뮬레이션하기 위한 **엣지 케이스 시나리오가 포함**되어 있습니다.', text)
text = re.sub(r'평가 로직이 정확히 작동하는지', '평가 로직이 정상 작동하는지', text)
text = re.sub(r'엔진이 결근을 정확히 감지하되', '엔진이 결근을 감지하되', text)
text = re.sub(r'상태를 정확히 반영합니다\.', '상태를 반영합니다.', text)
text = re.sub(r'정확히 계산되어 명세서에 합산되는지 확인\.', '산출되어 명세서에 합산되는지 확인.', text)
text = re.sub(r'평균 15시간\*\*을 엔진이 정확히 인지하여', '평균 15시간**을 엔진이 인지하여', text)
text = re.sub(r'차이가 정확히 반영되는지 검증\.', '차이가 반영되는지 검증.', text)
text = re.sub(r'수학적 정확성', '산출 결과', text)
text = re.sub(r'수학적 정확성은 113개 자동화 테스트로 보장하면서도', '산출 로직은 114개 자동화 테스트로 검증하면서도', text)
text = re.sub(r'수학적 정확성은 114개 자동화 테스트로 보장하면서도', '산출 로직은 114개 자동화 테스트로 검증하면서도', text)
text = re.sub(r'근거 증명', '결과 시뮬레이션', text)
text = re.sub(r'수학적으로 증명합니다\.', '수치로 시뮬레이션합니다.', text)
text = re.sub(r'\> \*\*증명\*\*:', '> **확인**:', text)
text = re.sub(r'발동 증명', '발동 시뮬레이션', text)
text = re.sub(r'정상 작동하는지 증명합니다\.', '정상 작동하는지 확인합니다.', text)
text = re.sub(r'산입 수치 증명', '산입 시뮬레이션', text)
text = re.sub(r'정확히 일치하는지', '일치하는지', text)
text = re.sub(r'\(정확히 5일 감소\)', '(5일 감소)', text)
text = re.sub(r'완전히 동기화되어', '동기화되어', text)
text = re.sub(r'시뮬레이션 증명', '시뮬레이션 결과', text)
text = re.sub(r'1원 이내 오차로 일치합니다\.', '오차 범위 내에서 일치합니다.', text)
text = re.sub(r'로직 증명', '로직 검증', text)
text = re.sub(r'수학적으로 증명되었음을 입증합니다\.', '시뮬레이션되었음을 확인합니다.', text)
text = re.sub(r'1원 이내로 일치하는지 검증합니다\.', '오차 범위 내에서 일치하는지 검증합니다.', text)
text = re.sub(r'통상임금 증명', '통상임금 비교', text)
text = re.sub(r'총액 차이 증명', '총액 차이 확인', text)
text = re.sub(r'정확히 15시간', '15시간 경계값', text)
text = re.sub(r'정확히 365일', '365일 경계값', text)

with open(path, 'w', encoding='utf-8') as f:
    f.write(text)
print("Replacements done.")
