// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // verify_web 전용 앱 (Firebase 콘솔에서 별도 등록)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlADFvi9QCuBIfrkMGzw9MIbggeCbLYhM',
    appId: '1:824353133931:web:a7b9b476d57a37d201e82e',
    messagingSenderId: '824353133931',
    projectId: 'standard-albapay',
    authDomain: 'standard-albapay.firebaseapp.com',
    storageBucket: 'standard-albapay.firebasestorage.app',
    measurementId: 'G-HFR84XYZ47',
  );
}
