name: verify_web
description: "AlbaPay 급여 계산 검증기"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  shared_logic:
    path: ../../packages/shared_logic

  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  cupertino_icons: ^1.0.8
  intl: any
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
